# Generated by Django 3.2.5 on 2021-07-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('km_driven', models.IntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(max_length=50)),
                ('transmission_type', models.CharField(max_length=50)),
                ('seller_type', models.CharField(max_length=50)),
                ('year_bought', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='uploads/Cars/')),
                ('owner', models.CharField(max_length=50)),
            ],
        ),
    ]
