# Generated by Django 3.2.5 on 2021-07-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('km_driven', models.IntegerField(blank=True, null=True)),
                ('seller_type', models.CharField(max_length=50)),
                ('year_bought', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='uploads/Bikes/')),
                ('owner', models.CharField(max_length=50)),
            ],
        ),
    ]
